USE ecommerce;

-- Populate tables with some test data

LOAD DATA LOCAL
    INFILE '/Users/Andy/Documents/GitHub/cse305/data/item_type.csv'
    INTO TABLE item_type
    CHARACTER SET UTF8
    FIELDS
        TERMINATED BY ','
    LINES 
        TERMINATED BY '\n'
    IGNORE 1 LINES;

LOAD DATA LOCAL
    INFILE '/Users/Andy/Documents/GitHub/cse305/data/item.csv'
    INTO TABLE item
    CHARACTER SET UTF8
    FIELDS
        TERMINATED BY ','
    LINES 
        TERMINATED BY '\n'
    IGNORE 1 LINES;

LOAD DATA LOCAL
    INFILE '/Users/Andy/Documents/GitHub/cse305/data/seller.csv'
    INTO TABLE seller
    CHARACTER SET UTF8
    FIELDS
        TERMINATED BY ','
    LINES 
        TERMINATED BY '\n'
    IGNORE 1 LINES;

LOAD DATA LOCAL
    INFILE '/Users/Andy/Documents/GitHub/cse305/data/customer.csv'
    INTO TABLE customer
    CHARACTER SET UTF8
    FIELDS
        TERMINATED BY ','
    LINES 
        TERMINATED BY '\n'
    IGNORE 1 LINES;

LOAD DATA LOCAL
    INFILE '/Users/Andy/Documents/GitHub/cse305/data/carrier.csv'
    INTO TABLE carrier
    CHARACTER SET UTF8
    FIELDS
        TERMINATED BY ','
    LINES 
        TERMINATED BY '\n'
    IGNORE 1 LINES;

-- error with loading in a NULL from a CSV for some reason..
-- LOAD DATA
--     INFILE '/var/lib/mysql-files/administrator.csv'
--     INTO TABLE administrator
--     CHARACTER SET UTF8
--     FIELDS
--         TERMINATED BY ','
--     LINES 
--         TERMINATED BY '\n'
--     IGNORE 1 LINES;

/* Mock SQL statements that would be generated by the backend */

-- Add employees
-- INSERT
--     INTO administrator(id,first_name,last_name,admin_role,date_joined,supervisor_id)
--     VALUES
--         (0,'Jondy','Song','Database Admin','2019-04-14',NULL);

-- Customers 0 and 1 add a billing and shipping address
INSERT 
    INTO address(customer_id, id, address_type, address1, address2, apt, city, zip)
    VALUES
        (1,0,0,'123 Main St',NULL,NULL,'Stony Brook','11790'),
        (1,0,1,'450 Circle Road','West Apartments',NULL,'Stony Brook','11790'),
        (2,0,0,'456 Main St',NULL,NULL,'Stony Brook','11790'),
        (2,0,1,'900 Circle Road','West Apartments',NULL,'Stony Brook','11790');

-- Sellers 1 and 4 update their stock
INSERT
    INTO sells(seller_id,item_id,price,stock)
    VALUES
        (1,1,999.99,10),
        (1,2,100.00,10),
        (1,3,50.00,10),
        (4,6,9999.99,10);

-- Customer 1 purchases 2 of item 1 from Seller 1 and ships to address 2
-- assuming 8% sales tax
INSERT
    INTO purchase(purchase_id,customer_id,item_id,quantity,total_cost,seller_id,purchase_date,address_id,card_number,card_expiry_date)
    VALUES
        (0,1,1,2,2159.98,1,CURDATE(),1,'1111','2020-07-01');

UPDATE sells
    SET stock = stock - 2
    WHERE seller_id = 1 AND item_id = 1;

INSERT
    INTO shipment(shipment_id,item_id,customer_id,purchase_id,address_id,carrier_id,tracking_number,process_date,arrival_date,shipping_fee)
    VALUES
        (0,1,1,1,2,1,'ABCD',CURDATE(),NULL,0.00);

-- Customer 2 purchases 1 of item 6 from Seller 4
INSERT
    INTO purchase(purchase_id,customer_id,item_id,quantity,total_cost,seller_id,purchase_date,address_id,card_number,card_expiry_date)
    VALUES
        (0,2,6,1,10799.99,4,CURDATE(),3,'2222','2020-07-01');

UPDATE sells
    SET stock = stock -1
    WHERE seller_id = 4 AND item_id = 6;

INSERT
    INTO shipment(shipment_id,item_id,customer_id,purchase_id,address_id,carrier_id,tracking_number,process_date,arrival_date,shipping_fee)
    VALUES
        (0,6,2,2,4,2,'EFGH',CURDATE(),NULL,0.00);

-- Carrier delivers Customer 1 his/her package
UPDATE shipment
    SET arrival_date = CURDATE()
    WHERE shipment_id = 1;

-- Carrier delivers Customer 2 his/her package
UPDATE shipment
    SET arrival_date = CURDATE()
    WHERE shipment_id = 2;

-- Customer 1 writes a review
INSERT
    INTO reviews(customer_id,item_id,seller_id,review_text,write_date)
    VALUES
        (1,1,1,"BEST FRIDGE EVER!!!",CURDATE());